Start study: Stiffened Wednesday, April 4, 2018 3:12:21 PM
End study: Stiffened Wednesday, April 4, 2018 3:12:48 PM
Start study: Original Wednesday, April 4, 2018 3:13:10 PM
End study: Original Wednesday, April 4, 2018 3:13:29 PM
Start study: Stiffened Friday, April 6, 2018 3:08:30 AM
End study: Stiffened Friday, April 6, 2018 3:08:52 AM
Start study: Original Friday, April 6, 2018 3:09:09 AM
End study: Original Friday, April 6, 2018 3:09:25 AM
Start study: Stiffened_40 Friday, April 6, 2018 3:09:35 AM
End study: Stiffened_40 Friday, April 6, 2018 3:09:56 AM
Start study: Original_40 Friday, April 6, 2018 3:10:14 AM
End study: Original_40 Friday, April 6, 2018 3:10:32 AM
Start study: Stiffened Tuesday, April 10, 2018 12:38:39 PM
End study: Stiffened Tuesday, April 10, 2018 12:38:58 PM
Start study: Stiffened_40 Tuesday, April 10, 2018 12:39:15 PM
End study: Stiffened_40 Tuesday, April 10, 2018 12:39:35 PM
Start study: Stiffened Tuesday, April 10, 2018 12:47:08 PM
End study: Stiffened Tuesday, April 10, 2018 12:47:28 PM
Start study: Stiffened_40 Tuesday, April 10, 2018 12:47:51 PM
End study: Stiffened_40 Tuesday, April 10, 2018 12:48:10 PM
Start study: Stiffened Tuesday, April 10, 2018 1:46:13 PM
Meshing failed. Terminating analysis.
End study: Stiffened Tuesday, April 10, 2018 1:46:13 PM
Start study: Stiffened_40 Tuesday, April 10, 2018 1:46:13 PM
Meshing failed. Terminating analysis.
End study: Stiffened_40 Tuesday, April 10, 2018 1:46:13 PM
Start study: Stiffened Tuesday, April 10, 2018 1:47:43 PM
End study: Stiffened Tuesday, April 10, 2018 1:48:16 PM
Start study: Stiffened_40 Tuesday, April 10, 2018 1:48:45 PM
End study: Stiffened_40 Tuesday, April 10, 2018 1:49:17 PM
Start study: Stiffened Friday, April 13, 2018 7:59:13 AM
End study: Stiffened Friday, April 13, 2018 8:00:01 AM
Start study: Stiffened_40 Friday, April 13, 2018 8:00:48 AM
End study: Stiffened_40 Friday, April 13, 2018 8:01:36 AM
Start study: Stiffened Sunday, April 22, 2018 2:39:01 PM
End study: Stiffened Sunday, April 22, 2018 2:39:44 PM
Start study: Stiffened_40 Sunday, April 22, 2018 2:40:43 PM
End study: Stiffened_40 Sunday, April 22, 2018 2:41:28 PM
