C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Core-45Degrees
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\RoundKeelCoreTest-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Stiffened
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Keel Design\Keel_Wide_Assembled-Original
