C:\Users\hejoh\Documents\GrabCAD\Sailbot\Ballast Design\MB Arm-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Ballast Design\MB Arm-Static 2
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Ballast Design\MB Arm-Static 3
C:\Users\hejoh\Documents\GrabCAD\Sailbot\wingsail assembly\New Main Sail\Counterweight\Counterweight arm rod-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\wingsail assembly\New Main Sail\Counterweight\Counterweight arm rod-Static 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\wingsail assembly\New Main Sail\Counterweight\Counterweight arm rod-Static 1
