C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 1
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal Fins
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
C:\Users\hejoh\Documents\GrabCAD\Sailbot\Electronics\MotorControllerEnclosure-Thermal 3 from [Thermal 1]
