R:\MQP\Sailbot_CAD\Keel Design\Keel_Core-Static 1
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core-Static 1
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core_Hex-Static 1
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core_Hex-Static 1
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core_Hex-Static 1
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core_Hex-Horizontal
R:\MQP\Sailbot_CAD\Keel Design\Keel_Core-45Degrees
R:\MQP\Sailbot Cad\Keel Design\Keel_bulb_Wide-SupportTest
