Start study: Static 1 Friday, November 3, 2017 6:56:30 PM
End study: Static 1 Friday, November 3, 2017 6:56:42 PM
Start study: Static 2 Friday, November 3, 2017 6:57:16 PM
End study: Static 2 Friday, November 3, 2017 6:57:33 PM
Start study: Static 1 Friday, November 3, 2017 6:59:28 PM
End study: Static 1 Friday, November 3, 2017 6:59:40 PM
Start study: Static 2 Friday, November 3, 2017 7:00:18 PM
End study: Static 2 Friday, November 3, 2017 7:00:35 PM
Start study: Static 1 Friday, November 3, 2017 7:04:05 PM
End study: Static 1 Friday, November 3, 2017 7:04:21 PM
Start study: Static 2 Friday, November 3, 2017 7:04:53 PM
End study: Static 2 Friday, November 3, 2017 7:05:09 PM
